### PR TITLE
Potato Updates

### PR DESCRIPTION
**Pull request by AliAryanTech**
Just little updates

### CODE REVIEW

**Review by LuckyYam — CHANGES_REQUESTED** [review]
LGTM, but run the command `yarn format` and update

**Review by LuckyYam — CHANGES_REQUESTED** [review]
Run `yarn format` for this too

**Comment by AliAryanTech** [comment]
> Run `yarn format` for this too

Where to run I don't have pc

**Comment by AliAryanTech** [comment]
> Run `yarn format` for this too

Btw, I test the code and it's working

**Comment by AliAryanTech** [comment]
IDK now

**Comment by AliAryanTech** [comment]
Ok retry

**Comment by AliAryanTech** [comment]
Ok retry

**Pull request closed without merging**
